services:
  - type: web
    name: theunnecessaryfm
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: NUM_CANDIDATES
        value: "1"
      - key: RENDER
        value: "1"
      - key: FILE_SIZE_LIMIT
        value: "5MB"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: BLIS_NUM_THREADS
        value: "1"
